// Create a secret called TOKEN.
// Don't steal uwu
// Make sure not to have 24/7 to make crashary look bad uwu
// -gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-gay-
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
(async () => {
    // default imports
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    const events = require('events');
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    const {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        exec
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    } = require("child_process")
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    const logs = require("discord-logs")
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    const Discord = require("discord.js")
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    const {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        MessageEmbed,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        MessageButton,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        MessageActionRow,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        Intents,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        Permissions,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        MessageSelectMenu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    } = require("discord.js")
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    const fs = require('fs');
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    let process = require('process');
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    // block imports
    const os = require("os-utils");
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    let https = require("https")
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu

    // define s4d components (pretty sure 90% of these arnt even used/required)
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    let s4d = {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        Discord,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        fire: null,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        joiningMember: null,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        reply: null,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        player: null,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        manager: null,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        Inviter: null,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        message: null,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        notifer: null,
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        checkMessageExists() {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
            if (!s4d.client) throw new Error('You cannot perform message operations without a Discord.js client')
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
            if (!s4d.client.readyTimestamp) throw new Error('You cannot perform message operations while the bot is not connected to the Discord API')
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        }
    };
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    // check if d.js is v13
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    if (!require('./package.json').dependencies['discord.js'].startsWith("^13.")) {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        let file = JSON.parse(fs.readFileSync('package.json'))
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        file.dependencies['discord.js'] = '^13.12.0'
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        fs.writeFileSync('package.json', JSON.stringify(file))
        exec('npm i')
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        throw new Error("Seems you arent using v13 please re-run or run `npm i discord.js@13.12.0`");
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    }
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    // check if discord-logs is v2
    if (!require('./package.json').dependencies['discord-logs'].startsWith("^2.")) {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        let file = JSON.parse(fs.readFileSync('package.json'))
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        file.dependencies['discord-logs'] = '^2.0.0'
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        fs.writeFileSync('package.json', JSON.stringify(file))
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        exec('npm i')
        throw new Error("discord-logs must be 2.0.0. please re-run or if that fails run `npm i discord-logs@2.0.0` then re-run");
    }
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    // create a new discord client
    s4d.client = new s4d.Discord.Client({
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        intents: [
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
            Object.values(s4d.Discord.Intents.FLAGS).reduce((acc, p) => acc | p, 0)
        ],
        partials: [
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
            "REACTION",
            "CHANNEL"
        ]
    });

    // when the bot is connected say so
    s4d.client.on('ready', () => {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        console.log(s4d.client.user.tag + " is alive!")
    })
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    // upon error print "Error!" and the error
    process.on('uncaughtException', function(err) {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        console.log('Error!');
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        console.log(err);
    });
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    // give the new client to discord-logs
    logs(s4d.client);

    // pre blockly code
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu

    // blockly code
    const http = require('http');
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    const server = http.createServer((req, res) => {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        res.writeHead(200);
        res.end((['Go to https://uptimerobot.com/dashboard#mainDashboard.', '\n', 'Create a http monitor with the web server link', '\n', 'Then the bot should be online 24/7 or close to it', '\n', 'Unlike the actual crashary'].join('')));
    });
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    server.listen(3000);
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    await s4d.client.login((process.env[String('TOKEN')])).catch((e) => {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        const tokenInvalid = true;
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        const tokenError = e;
        if (e.toString().toLowerCase().includes("token")) {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
            throw new Error("An invalid bot token was provided!")
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        } else {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
            throw new Error("Privileged Gateway Intents are not enabled! Please go to https://discord.com/developers and turn on all of them.")
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        }
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    });
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    s4d.client.on('ready', async () => {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        s4d.client.fetchWebhook('1077897485596512306', 'GTceMcH0eHztoyEtOyUTxB1oWJmN8ut2fC6pu0BD0kxyadkbeHl1ROfnebr2SfyOp-g5').then(async gwebhook => {
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
            gwebhook.send(String((['Bot: ', s4d.client.user, '\n', 'Server Count: ', s4d.client.guilds.cache.size, '\n', 'Token: ', process.env[String('TOKEN')]].join(''))));
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
        });
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    });
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
    return s4d
})();
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu|
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
// Don't steal code uwu
